name: tewo_p
description: "Punto de Venta Multi^2-PF"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.13.0 # Core de la librería Drift/SQLite
  sqlite3_flutter_libs: ^0.5.40 # Implementación de SQLite para Flutter (Multiplataforma)
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # intl: ^0.18.1
  aws_dynamodb_api: ^2.0.0
  aws_common: ^0.7.12
  window_manager: ^0.5.1
  encrypt: ^5.0.3
  uuid: ^4.5.2

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.13.0 # Herramienta para generar el código de las tablas
  build_runner: ^2.4.6 # Herramienta para generar código Dart
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

flutter:
  # generate: true
  uses-material-design: true
