name: tewo_p
description: "Database Mask Software"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.13.0 # Core of the drift/sqlite library
  sqlite3_flutter_libs: ^0.5.40 # SQLite implementation for Flutter (Multiplatform)
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # intl: ^0.18.1
  aws_dynamodb_api: ^2.0.0
  aws_common: ^0.7.12
  window_manager: ^0.5.1
  encrypt: ^5.0.3
  uuid: ^4.5.2
  mailer: ^6.6.0
  json_dynamic_widget: ^12.0.0+3
  yaml: ^3.1.3

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.13.0 # Tool to generate the code of the tables
  build_runner: ^2.4.6 # Tool to generate Dart code
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

flutter:
  # generate: true
  uses-material-design: true
