name: tewo_p
description: "Punto de Venta Multi^2-PF"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.13.0 # Core de la librería Drift/SQLite
  sqlite3_flutter_libs: ^0.5.40 # Implementación de SQLite para Flutter (Multiplataforma)
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.13.0 # Herramienta para generar el código de las tablas
  build_runner: ^2.4.6 # Herramienta para generar código Dart

flutter:
  uses-material-design: true
